/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_emulatorstate_free: (a: number, b: number) => void;
export const emulatorstate_af: (a: number) => number;
export const emulatorstate_bc: (a: number) => number;
export const emulatorstate_de: (a: number) => number;
export const emulatorstate_flags: (a: number) => number;
export const emulatorstate_framebuffer_ptr: (a: number) => number;
export const emulatorstate_frames: (a: number) => number;
export const emulatorstate_halted: (a: number) => number;
export const emulatorstate_hl: (a: number) => number;
export const emulatorstate_ie_reg: (a: number) => number;
export const emulatorstate_if_reg: (a: number) => number;
export const emulatorstate_ime: (a: number) => number;
export const emulatorstate_is_paused: (a: number) => number;
export const emulatorstate_lcdc: (a: number) => number;
export const emulatorstate_load_save_wasm: (a: number, b: number, c: number) => void;
export const emulatorstate_ly: (a: number) => number;
export const emulatorstate_new: (a: number, b: number) => number;
export const emulatorstate_pc: (a: number) => number;
export const emulatorstate_save_wasm: (a: number) => [number, number];
export const emulatorstate_set_paused: (a: number, b: number) => void;
export const emulatorstate_sp: (a: number) => number;
export const emulatorstate_stat: (a: number) => number;
export const emulatorstate_tick_frame: (a: number) => void;
export const emulatorstate_tick_step: (a: number) => void;
export const emulatorstate_update_joypad: (a: number, b: number, c: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_start: () => void;
